/* Generated By:JavaCC: Do not edit this line. ELParser.java */
package org.boc.rule.format;

import org.boc.rule.*;

import java.util.*;
import java.io.*;
/**
 * Generated EL parser.
 * 
 * @author Nathan Abramson
 * @author Shawn Bayern
 */

public class ELParser implements ELParserConstants {
  ExpressionFormatter formatter = new ExpressionFormatter();
  boolean isFunction = false;
  boolean isPrefix = false;

  public void setFormatter(ExpressionFormatter formatter)
  {
    this.formatter = formatter;
  }
  public static void main(String args[])
       throws ParseException
  {
    ELParser parser = new ELParser (System.in);
    parser.formatter.start();
    parser.Expressions ();
    parser.formatter.finish();
  }
  public void processSpecial(Token t)
  {
    if (t.specialToken == null) return;
    // The above statement determines that there are no special tokens
    // and returns control to the caller.
    Token tmp_t = t.specialToken;
    while (tmp_t.specialToken != null) tmp_t = tmp_t.specialToken;
    // The above line walks back the special token chain until it
    // reaches the first special token after the previous regular
    // token.
    while (tmp_t != null) {
      if ( "\n".equals(tmp_t.image) ) {
        this.formatter.newline(tmp_t.image);
      }
      else
        this.formatter.space(tmp_t.image);
      tmp_t = tmp_t.next;
    }
    // The above loop now walks the special token chain in the forward
    // direction printing them in the proce
  }

/*****************************************
 * GRAMMAR PRODUCTIONS *
 *****************************************/
  final public void Statement() throws ParseException {
    if (jj_2_1(2)) {
      ExpressionStatement();
    } else {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case STATEMENT_START:
        CompoundStatement();
        break;
      case IF1:
      case IF2:
      case IF3:
        IfThenElseExpression();
        break;
      default:
        jj_la1[0] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }

  }

  final public void Expressions() throws ParseException {
    label_1:
    while (true) {
      Statement();
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case INTEGER_LITERAL:
      case FLOATING_POINT_LITERAL:
      case STRING_LITERAL:
      case TRUE1:
      case TRUE2:
      case FALSE1:
      case FALSE2:
      case NULL:
      case LPAREN1:
      case LPAREN2:
      case SEMI1:
      case SEMI2:
      case MINUS1:
      case MINUS2:
      case MINUS3:
      case MINUS4:
      case NOT1:
      case NOT2:
      case NOT3:
      case EMPTY:
      case IF1:
      case IF2:
      case IF3:
      case STATEMENT_START:
      case IDENTIFIER:
        ;
        break;
      default:
        jj_la1[1] = jj_gen;
        break label_1;
      }
    }

  }

  final public void CompoundStatement() throws ParseException {
  Token t;
    t = jj_consume_token(STATEMENT_START);
      processSpecial(t); formatter.keyword(t.image);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case INTEGER_LITERAL:
    case FLOATING_POINT_LITERAL:
    case STRING_LITERAL:
    case TRUE1:
    case TRUE2:
    case FALSE1:
    case FALSE2:
    case NULL:
    case LPAREN1:
    case LPAREN2:
    case SEMI1:
    case SEMI2:
    case MINUS1:
    case MINUS2:
    case MINUS3:
    case MINUS4:
    case NOT1:
    case NOT2:
    case NOT3:
    case EMPTY:
    case IF1:
    case IF2:
    case IF3:
    case STATEMENT_START:
    case IDENTIFIER:
      Expressions();
      break;
    default:
      jj_la1[2] = jj_gen;
      ;
    }
    t = jj_consume_token(STATEMENT_END);
      processSpecial(t); formatter.keyword(t.image);

  }

  final public void ExpressionStatement() throws ParseException {
  Token t;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case INTEGER_LITERAL:
    case FLOATING_POINT_LITERAL:
    case STRING_LITERAL:
    case TRUE1:
    case TRUE2:
    case FALSE1:
    case FALSE2:
    case NULL:
    case LPAREN1:
    case LPAREN2:
    case MINUS1:
    case MINUS2:
    case MINUS3:
    case MINUS4:
    case NOT1:
    case NOT2:
    case NOT3:
    case EMPTY:
    case IDENTIFIER:
      ExpressionSet();
      break;
    default:
      jj_la1[3] = jj_gen;
      ;
    }
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case SEMI1:
      t = jj_consume_token(SEMI1);
      break;
    case SEMI2:
      t = jj_consume_token(SEMI2);
      break;
    default:
      jj_la1[4] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
      processSpecial(t); formatter.keyword(t.image);

  }

  final public void ExpressionSet() throws ParseException {
  Token t;
    Expression();
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case COMMA1:
      case COMMA2:
        ;
        break;
      default:
        jj_la1[5] = jj_gen;
        break label_2;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case COMMA1:
        t = jj_consume_token(COMMA1);
        break;
      case COMMA2:
        t = jj_consume_token(COMMA2);
        break;
      default:
        jj_la1[6] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
          processSpecial(t); formatter.keyword(t.image);
      Expression();
    }

  }

  final public void SpecialEqualExpression() throws ParseException {
  Token t;
    NamedValue();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case ADDEQ1:
    case ADDEQ2:
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case ADDEQ1:
        t = jj_consume_token(ADDEQ1);
        break;
      case ADDEQ2:
        t = jj_consume_token(ADDEQ2);
        break;
      default:
        jj_la1[7] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
        processSpecial(t); formatter.keyword(t.image);
      break;
    case MINUSEQ1:
    case MINUSEQ2:
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case MINUSEQ1:
        t = jj_consume_token(MINUSEQ1);
        break;
      case MINUSEQ2:
        t = jj_consume_token(MINUSEQ2);
        break;
      default:
        jj_la1[8] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
        processSpecial(t); formatter.keyword(t.image);
      break;
    default:
      jj_la1[9] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    Expression();

  }

  final public void IfThenElseExpression() throws ParseException {
  Token t;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case IF1:
      t = jj_consume_token(IF1);
      break;
    case IF2:
      t = jj_consume_token(IF2);
      break;
    case IF3:
      t = jj_consume_token(IF3);
      break;
    default:
      jj_la1[10] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
      processSpecial(t); formatter.keyword(t.image);
    OrExpression();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case THEN1:
      t = jj_consume_token(THEN1);
      break;
    case THEN2:
      t = jj_consume_token(THEN2);
      break;
    case THEN3:
      t = jj_consume_token(THEN3);
      break;
    default:
      jj_la1[11] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
      processSpecial(t); formatter.keyword(t.image);
    Statement();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case ELSE1:
    case ELSE2:
    case ELSE3:
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case ELSE1:
        t = jj_consume_token(ELSE1);
        break;
      case ELSE2:
        t = jj_consume_token(ELSE2);
        break;
      case ELSE3:
        t = jj_consume_token(ELSE3);
        break;
      default:
        jj_la1[12] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
        processSpecial(t); formatter.keyword(t.image);
      Statement();
      break;
    default:
      jj_la1[13] = jj_gen;
      ;
    }

  }

  final public void LetExpression() throws ParseException {
   Token t;
    NamedValue();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case EQUAL1:
      t = jj_consume_token(EQUAL1);
      break;
    case EQUAL2:
      t = jj_consume_token(EQUAL2);
      break;
    case EQUAL3:
      t = jj_consume_token(EQUAL3);
      break;
    case EQUAL4:
      t = jj_consume_token(EQUAL4);
      break;
    default:
      jj_la1[14] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
      processSpecial(t); formatter.keyword(t.image);
    Expression();

  }

  final public void Expression() throws ParseException {
  Token t;
    if (jj_2_2(2147483647)) {
      ConditionalExpression();
    } else if (jj_2_3(2147483647)) {
      LetExpression();
    } else if (jj_2_4(2147483647)) {
      SpecialEqualExpression();
    } else {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case INTEGER_LITERAL:
      case FLOATING_POINT_LITERAL:
      case STRING_LITERAL:
      case TRUE1:
      case TRUE2:
      case FALSE1:
      case FALSE2:
      case NULL:
      case LPAREN1:
      case LPAREN2:
      case MINUS1:
      case MINUS2:
      case MINUS3:
      case MINUS4:
      case NOT1:
      case NOT2:
      case NOT3:
      case EMPTY:
      case IDENTIFIER:
        OrExpression();
        break;
      default:
        jj_la1[15] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }

  }

  final public void OrExpression() throws ParseException {
  Token t;
    AndExpression();
    label_3:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case OR1:
      case OR2:
      case OR3:
        ;
        break;
      default:
        jj_la1[16] = jj_gen;
        break label_3;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case OR1:
        t = jj_consume_token(OR1);
        break;
      case OR2:
        t = jj_consume_token(OR2);
        break;
      case OR3:
        t = jj_consume_token(OR3);
        break;
      default:
        jj_la1[17] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
        processSpecial(t); formatter.keyword(t.image);
      AndExpression();
    }

  }

  final public void AndExpression() throws ParseException {
  Token t;
    EqualityExpression();
    label_4:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case AND1:
      case AND2:
      case AND3:
        ;
        break;
      default:
        jj_la1[18] = jj_gen;
        break label_4;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case AND1:
        t = jj_consume_token(AND1);
        break;
      case AND2:
        t = jj_consume_token(AND2);
        break;
      case AND3:
        t = jj_consume_token(AND3);
        break;
      default:
        jj_la1[19] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
        processSpecial(t); formatter.keyword(t.image);
      EqualityExpression();
    }

  }

  final public void EqualityExpression() throws ParseException {
  Token t;
    RelationalExpression();
    label_5:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case EQ1:
      case EQ2:
      case EQ3:
      case NE1:
      case NE2:
      case NE3:
        ;
        break;
      default:
        jj_la1[20] = jj_gen;
        break label_5;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case EQ1:
      case EQ2:
      case EQ3:
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case EQ1:
          t = jj_consume_token(EQ1);
          break;
        case EQ2:
          t = jj_consume_token(EQ2);
          break;
        case EQ3:
          t = jj_consume_token(EQ3);
          break;
        default:
          jj_la1[21] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        processSpecial(t); formatter.keyword(t.image);
        break;
      case NE1:
      case NE2:
      case NE3:
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case NE1:
          t = jj_consume_token(NE1);
          break;
        case NE2:
          t = jj_consume_token(NE2);
          break;
        case NE3:
          t = jj_consume_token(NE3);
          break;
        default:
          jj_la1[22] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        processSpecial(t); formatter.keyword(t.image);
        break;
      default:
        jj_la1[23] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      RelationalExpression();
    }

  }

  final public void RelationalExpression() throws ParseException {
  Token t;
    AddExpression();
    label_6:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case GT1:
      case GT2:
      case GT3:
      case GT4:
      case LT1:
      case LT2:
      case LT3:
      case LT4:
      case LE1:
      case LE2:
      case LE3:
      case LE4:
      case GE1:
      case GE2:
      case GE3:
      case GE4:
        ;
        break;
      default:
        jj_la1[24] = jj_gen;
        break label_6;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case LT1:
      case LT2:
      case LT3:
      case LT4:
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case LT1:
          t = jj_consume_token(LT1);
          break;
        case LT2:
          t = jj_consume_token(LT2);
          break;
        case LT3:
          t = jj_consume_token(LT3);
          break;
        case LT4:
          t = jj_consume_token(LT4);
          break;
        default:
          jj_la1[25] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        processSpecial(t); formatter.keyword(t.image);
        break;
      case GT1:
      case GT2:
      case GT3:
      case GT4:
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case GT1:
          t = jj_consume_token(GT1);
          break;
        case GT2:
          t = jj_consume_token(GT2);
          break;
        case GT3:
          t = jj_consume_token(GT3);
          break;
        case GT4:
          t = jj_consume_token(GT4);
          break;
        default:
          jj_la1[26] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        processSpecial(t); formatter.keyword(t.image);
        break;
      case GE1:
      case GE2:
      case GE3:
      case GE4:
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case GE1:
          t = jj_consume_token(GE1);
          break;
        case GE2:
          t = jj_consume_token(GE2);
          break;
        case GE3:
          t = jj_consume_token(GE3);
          break;
        case GE4:
          t = jj_consume_token(GE4);
          break;
        default:
          jj_la1[27] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        processSpecial(t); formatter.keyword(t.image);
        break;
      case LE1:
      case LE2:
      case LE3:
      case LE4:
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case LE1:
          t = jj_consume_token(LE1);
          break;
        case LE2:
          t = jj_consume_token(LE2);
          break;
        case LE3:
          t = jj_consume_token(LE3);
          break;
        case LE4:
          t = jj_consume_token(LE4);
          break;
        default:
          jj_la1[28] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        processSpecial(t); formatter.keyword(t.image);
        break;
      default:
        jj_la1[29] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      AddExpression();
    }

  }

  final public void AddExpression() throws ParseException {
  Token t;
    MultiplyExpression();
    label_7:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case PLUS1:
      case PLUS2:
      case PLUS3:
      case PLUS4:
      case MINUS1:
      case MINUS2:
      case MINUS3:
      case MINUS4:
        ;
        break;
      default:
        jj_la1[30] = jj_gen;
        break label_7;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case PLUS1:
      case PLUS2:
      case PLUS3:
      case PLUS4:
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case PLUS1:
          t = jj_consume_token(PLUS1);
          break;
        case PLUS2:
          t = jj_consume_token(PLUS2);
          break;
        case PLUS3:
          t = jj_consume_token(PLUS3);
          break;
        case PLUS4:
          t = jj_consume_token(PLUS4);
          break;
        default:
          jj_la1[31] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        processSpecial(t); formatter.keyword(t.image);
        break;
      case MINUS1:
      case MINUS2:
      case MINUS3:
      case MINUS4:
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case MINUS1:
          t = jj_consume_token(MINUS1);
          break;
        case MINUS2:
          t = jj_consume_token(MINUS2);
          break;
        case MINUS3:
          t = jj_consume_token(MINUS3);
          break;
        case MINUS4:
          t = jj_consume_token(MINUS4);
          break;
        default:
          jj_la1[32] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        processSpecial(t); formatter.keyword(t.image);
        break;
      default:
        jj_la1[33] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      MultiplyExpression();
    }

  }

  final public void MultiplyExpression() throws ParseException {
  Token t;
    UnaryExpression();
    label_8:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case MULTIPLY1:
      case MULTIPLY2:
      case MULTIPLY3:
      case DIVIDE1:
      case DIVIDE2:
      case DIVIDE3:
      case DIVIDE4:
      case MODULUS1:
      case MODULUS2:
        ;
        break;
      default:
        jj_la1[34] = jj_gen;
        break label_8;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case MULTIPLY1:
      case MULTIPLY2:
      case MULTIPLY3:
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case MULTIPLY1:
          t = jj_consume_token(MULTIPLY1);
          break;
        case MULTIPLY2:
          t = jj_consume_token(MULTIPLY2);
          break;
        case MULTIPLY3:
          t = jj_consume_token(MULTIPLY3);
          break;
        default:
          jj_la1[35] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        processSpecial(t); formatter.keyword(t.image);
        break;
      case DIVIDE1:
      case DIVIDE2:
      case DIVIDE3:
      case DIVIDE4:
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case DIVIDE1:
          t = jj_consume_token(DIVIDE1);
          break;
        case DIVIDE2:
          t = jj_consume_token(DIVIDE2);
          break;
        case DIVIDE3:
          t = jj_consume_token(DIVIDE3);
          break;
        case DIVIDE4:
          t = jj_consume_token(DIVIDE4);
          break;
        default:
          jj_la1[36] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        processSpecial(t); formatter.keyword(t.image);
        break;
      case MODULUS1:
      case MODULUS2:
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case MODULUS1:
          t = jj_consume_token(MODULUS1);
          break;
        case MODULUS2:
          t = jj_consume_token(MODULUS2);
          break;
        default:
          jj_la1[37] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        processSpecial(t); formatter.keyword(t.image);
        break;
      default:
        jj_la1[38] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      UnaryExpression();
    }

  }

  final public void ConditionalExpression() throws ParseException {
  Token t;
    OrExpression();
    t = jj_consume_token(COND);
    processSpecial(t); formatter.keyword(t.image);
    Expression();
    t = jj_consume_token(COLON);
    processSpecial(t); formatter.keyword(t.image);
    Expression();

  }

  final public void UnaryExpression() throws ParseException {
  Token t;
    label_9:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case MINUS1:
      case MINUS2:
      case MINUS3:
      case MINUS4:
      case NOT1:
      case NOT2:
      case NOT3:
      case EMPTY:
        ;
        break;
      default:
        jj_la1[39] = jj_gen;
        break label_9;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case NOT1:
      case NOT2:
      case NOT3:
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case NOT1:
          t = jj_consume_token(NOT1);
          break;
        case NOT2:
          t = jj_consume_token(NOT2);
          break;
        case NOT3:
          t = jj_consume_token(NOT3);
          break;
        default:
          jj_la1[40] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      processSpecial(t); formatter.keyword(t.image);
        break;
      case MINUS1:
      case MINUS2:
      case MINUS3:
      case MINUS4:
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case MINUS1:
          t = jj_consume_token(MINUS1);
          break;
        case MINUS2:
          t = jj_consume_token(MINUS2);
          break;
        case MINUS3:
          t = jj_consume_token(MINUS3);
          break;
        case MINUS4:
          t = jj_consume_token(MINUS4);
          break;
        default:
          jj_la1[41] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      processSpecial(t); formatter.keyword(t.image);
        break;
      case EMPTY:
        t = jj_consume_token(EMPTY);
      processSpecial(t); formatter.keyword(t.image);
        break;
      default:
        jj_la1[42] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    Value();

  }

  final public void Value() throws ParseException {
  Token t;
    ValuePrefix();
    label_10:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case DOT:
      case LBRACKET:
        ;
        break;
      default:
        jj_la1[43] = jj_gen;
        break label_10;
      }
      ValueSuffix();
    }

  }

/**
 * This is an element that can start a value
 **/
  final public void ValuePrefix() throws ParseException {
  Token t;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case INTEGER_LITERAL:
    case FLOATING_POINT_LITERAL:
    case STRING_LITERAL:
    case TRUE1:
    case TRUE2:
    case FALSE1:
    case FALSE2:
    case NULL:
      Literal();
      break;
    case LPAREN1:
    case LPAREN2:
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case LPAREN1:
        t = jj_consume_token(LPAREN1);
        break;
      case LPAREN2:
        t = jj_consume_token(LPAREN2);
        break;
      default:
        jj_la1[44] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
       processSpecial(t); formatter.keyword(t.image);
      Expression();
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case RPAREN1:
        t = jj_consume_token(RPAREN1);
        break;
      case RPAREN2:
        t = jj_consume_token(RPAREN2);
        break;
      default:
        jj_la1[45] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
       processSpecial(t); formatter.keyword(t.image);
      break;
    default:
      jj_la1[46] = jj_gen;
      if (jj_2_5(2147483647)) {
                                                         isFunction=true;
        FunctionInvocation();
      } else {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case IDENTIFIER:
          NamedValue();
          break;
        default:
          jj_la1[47] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    }

  }

  final public void NamedValue() throws ParseException {
  Token t;
    t = jj_consume_token(IDENTIFIER);
    processSpecial(t); formatter.variable(t.image);
  }

  final public void FunctionInvocation() throws ParseException {
  Token t;
    QualifiedName();
     isFunction = false;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case LPAREN1:
      t = jj_consume_token(LPAREN1);
      break;
    case LPAREN2:
      t = jj_consume_token(LPAREN2);
      break;
    default:
      jj_la1[48] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
     processSpecial(t); formatter.keyword(t.image);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case INTEGER_LITERAL:
    case FLOATING_POINT_LITERAL:
    case STRING_LITERAL:
    case TRUE1:
    case TRUE2:
    case FALSE1:
    case FALSE2:
    case NULL:
    case LPAREN1:
    case LPAREN2:
    case MINUS1:
    case MINUS2:
    case MINUS3:
    case MINUS4:
    case NOT1:
    case NOT2:
    case NOT3:
    case EMPTY:
    case IDENTIFIER:
      Expression();
      label_11:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case COMMA1:
        case COMMA2:
          ;
          break;
        default:
          jj_la1[49] = jj_gen;
          break label_11;
        }
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case COMMA1:
          t = jj_consume_token(COMMA1);
          break;
        case COMMA2:
          t = jj_consume_token(COMMA2);
          break;
        default:
          jj_la1[50] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
          processSpecial(t); formatter.keyword(t.image);
        Expression();
      }
      break;
    default:
      jj_la1[51] = jj_gen;
      ;
    }
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case RPAREN1:
      t = jj_consume_token(RPAREN1);
      break;
    case RPAREN2:
      t = jj_consume_token(RPAREN2);
      break;
    default:
      jj_la1[52] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
     processSpecial(t); formatter.keyword(t.image);

  }

  final public void ValueSuffix() throws ParseException {
  Token t;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case DOT:
      PropertySuffix();
      break;
    case LBRACKET:
      ArraySuffix();
      break;
    default:
      jj_la1[53] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }

  }

  final public void PropertySuffix() throws ParseException {
  Token t;
    t = jj_consume_token(DOT);
     processSpecial(t); formatter.property(t.image);
    Identifier();

  }

  final public void ArraySuffix() throws ParseException {
  Token t;
    t = jj_consume_token(LBRACKET);
       processSpecial(t); formatter.keyword(t.image);
    Expression();
    t = jj_consume_token(RBRACKET);
       processSpecial(t); formatter.keyword(t.image);

  }

  final public void Literal() throws ParseException {
  Token t;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case TRUE1:
    case TRUE2:
    case FALSE1:
    case FALSE2:
      BooleanLiteral();
      break;
    case INTEGER_LITERAL:
      IntegerLiteral();
      break;
    case FLOATING_POINT_LITERAL:
      FloatingPointLiteral();
      break;
    case STRING_LITERAL:
      StringLiteral();
      break;
    case NULL:
      NullLiteral();
      break;
    default:
      jj_la1[54] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }

  }

  final public void BooleanLiteral() throws ParseException {
  Token t;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case TRUE1:
    case TRUE2:
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case TRUE1:
        t = jj_consume_token(TRUE1);
        break;
      case TRUE2:
        t = jj_consume_token(TRUE2);
        break;
      default:
        jj_la1[55] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    processSpecial(t); formatter.constant(t.image);
      break;
    case FALSE1:
    case FALSE2:
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case FALSE1:
        t = jj_consume_token(FALSE1);
        break;
      case FALSE2:
        t = jj_consume_token(FALSE2);
        break;
      default:
        jj_la1[56] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    processSpecial(t); formatter.constant(t.image);
      break;
    default:
      jj_la1[57] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public void StringLiteral() throws ParseException {
  Token t;
    t = jj_consume_token(STRING_LITERAL);
    processSpecial(t); formatter.constant(t.image);
  }

  final public void IntegerLiteral() throws ParseException {
  Token t;
    t = jj_consume_token(INTEGER_LITERAL);
    processSpecial(t); formatter.constant(t.image);
  }

  final public void FloatingPointLiteral() throws ParseException {
  Token t;
    t = jj_consume_token(FLOATING_POINT_LITERAL);
    processSpecial(t); formatter.constant(t.image);
  }

  final public void NullLiteral() throws ParseException {
  Token t;
    t = jj_consume_token(NULL);
    processSpecial(t); formatter.constant(t.image);
  }

  final public void Identifier() throws ParseException {
  Token t;
    t = jj_consume_token(IDENTIFIER);
    processSpecial(t);
    if ( isPrefix ) {
      formatter.keyword(t.image);
    }
    else {
      if (isFunction) {
        formatter.function(t.image);
      }
      else {
        formatter.variable(t.image);
      }
    }
  }

  final public void QualifiedName() throws ParseException {
  Token t = null;
    if (jj_2_6(2147483647)) {
       isPrefix=true;
      Identifier();
       isPrefix=false;
      t = jj_consume_token(COLON);
        processSpecial(t); formatter.keyword(t.image);
    } else {
      ;
    }
    Identifier();

  }

  final private boolean jj_2_1(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_1(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  final private boolean jj_2_2(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_2(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  final private boolean jj_2_3(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_3(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(2, xla); }
  }

  final private boolean jj_2_4(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_4(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(3, xla); }
  }

  final private boolean jj_2_5(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_5(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(4, xla); }
  }

  final private boolean jj_2_6(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_6(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(5, xla); }
  }

  final private boolean jj_3R_14() {
    if (jj_3R_21()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(74)) {
    jj_scanpos = xsp;
    if (jj_scan_token(75)) {
    jj_scanpos = xsp;
    if (jj_scan_token(76)) {
    jj_scanpos = xsp;
    if (jj_scan_token(77)) return true;
    }
    }
    }
    if (jj_3R_20()) return true;
    return false;
  }

  final private boolean jj_3R_60() {
    if (jj_3R_65()) return true;
    return false;
  }

  final private boolean jj_3R_52() {
    if (jj_3R_59()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_60()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  final private boolean jj_3R_58() {
    if (jj_scan_token(EMPTY)) return true;
    return false;
  }

  final private boolean jj_3R_17() {
    if (jj_scan_token(IDENTIFIER)) return true;
    return false;
  }

  final private boolean jj_3R_57() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(50)) {
    jj_scanpos = xsp;
    if (jj_scan_token(51)) {
    jj_scanpos = xsp;
    if (jj_scan_token(52)) {
    jj_scanpos = xsp;
    if (jj_scan_token(53)) return true;
    }
    }
    }
    return false;
  }

  final private boolean jj_3R_56() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(63)) {
    jj_scanpos = xsp;
    if (jj_scan_token(64)) {
    jj_scanpos = xsp;
    if (jj_scan_token(65)) return true;
    }
    }
    return false;
  }

  final private boolean jj_3R_51() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_56()) {
    jj_scanpos = xsp;
    if (jj_3R_57()) {
    jj_scanpos = xsp;
    if (jj_3R_58()) return true;
    }
    }
    return false;
  }

  final private boolean jj_3R_82() {
    if (jj_scan_token(NULL)) return true;
    return false;
  }

  final private boolean jj_3R_23() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(89)) {
    jj_scanpos = xsp;
    if (jj_scan_token(90)) return true;
    }
    return false;
  }

  final private boolean jj_3R_47() {
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_51()) { jj_scanpos = xsp; break; }
    }
    if (jj_3R_52()) return true;
    return false;
  }

  final private boolean jj_3R_22() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(87)) {
    jj_scanpos = xsp;
    if (jj_scan_token(88)) return true;
    }
    return false;
  }

  final private boolean jj_3R_80() {
    if (jj_scan_token(FLOATING_POINT_LITERAL)) return true;
    return false;
  }

  final private boolean jj_3R_15() {
    if (jj_3R_21()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_22()) {
    jj_scanpos = xsp;
    if (jj_3R_23()) return true;
    }
    if (jj_3R_20()) return true;
    return false;
  }

  final private boolean jj_3R_13() {
    if (jj_3R_19()) return true;
    if (jj_scan_token(COND)) return true;
    if (jj_3R_20()) return true;
    if (jj_scan_token(COLON)) return true;
    if (jj_3R_20()) return true;
    return false;
  }

  final private boolean jj_3R_79() {
    if (jj_scan_token(INTEGER_LITERAL)) return true;
    return false;
  }

  final private boolean jj_3R_32() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(41)) {
    jj_scanpos = xsp;
    if (jj_scan_token(42)) return true;
    }
    return false;
  }

  final private boolean jj_3R_55() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(61)) {
    jj_scanpos = xsp;
    if (jj_scan_token(62)) return true;
    }
    return false;
  }

  final private boolean jj_3R_54() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(57)) {
    jj_scanpos = xsp;
    if (jj_scan_token(58)) {
    jj_scanpos = xsp;
    if (jj_scan_token(59)) {
    jj_scanpos = xsp;
    if (jj_scan_token(60)) return true;
    }
    }
    }
    return false;
  }

  final private boolean jj_3R_25() {
    if (jj_3R_20()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_32()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  final private boolean jj_3R_81() {
    if (jj_scan_token(STRING_LITERAL)) return true;
    return false;
  }

  final private boolean jj_3R_53() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(54)) {
    jj_scanpos = xsp;
    if (jj_scan_token(55)) {
    jj_scanpos = xsp;
    if (jj_scan_token(56)) return true;
    }
    }
    return false;
  }

  final private boolean jj_3R_48() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_53()) {
    jj_scanpos = xsp;
    if (jj_3R_54()) {
    jj_scanpos = xsp;
    if (jj_3R_55()) return true;
    }
    }
    if (jj_3R_47()) return true;
    return false;
  }

  final private boolean jj_3R_18() {
    if (jj_3R_25()) return true;
    return false;
  }

  final private boolean jj_3R_41() {
    if (jj_3R_47()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_48()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  final private boolean jj_3R_85() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(9)) {
    jj_scanpos = xsp;
    if (jj_scan_token(10)) return true;
    }
    return false;
  }

  final private boolean jj_3R_84() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(7)) {
    jj_scanpos = xsp;
    if (jj_scan_token(8)) return true;
    }
    return false;
  }

  final private boolean jj_3R_78() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_84()) {
    jj_scanpos = xsp;
    if (jj_3R_85()) return true;
    }
    return false;
  }

  final private boolean jj_3R_12() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_18()) jj_scanpos = xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(39)) {
    jj_scanpos = xsp;
    if (jj_scan_token(40)) return true;
    }
    return false;
  }

  final private boolean jj_3R_50() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(50)) {
    jj_scanpos = xsp;
    if (jj_scan_token(51)) {
    jj_scanpos = xsp;
    if (jj_scan_token(52)) {
    jj_scanpos = xsp;
    if (jj_scan_token(53)) return true;
    }
    }
    }
    return false;
  }

  final private boolean jj_3R_49() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(46)) {
    jj_scanpos = xsp;
    if (jj_scan_token(47)) {
    jj_scanpos = xsp;
    if (jj_scan_token(48)) {
    jj_scanpos = xsp;
    if (jj_scan_token(49)) return true;
    }
    }
    }
    return false;
  }

  final private boolean jj_3R_74() {
    if (jj_3R_82()) return true;
    return false;
  }

  final private boolean jj_3R_42() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_49()) {
    jj_scanpos = xsp;
    if (jj_3R_50()) return true;
    }
    if (jj_3R_41()) return true;
    return false;
  }

  final private boolean jj_3R_73() {
    if (jj_3R_81()) return true;
    return false;
  }

  final private boolean jj_3R_72() {
    if (jj_3R_80()) return true;
    return false;
  }

  final private boolean jj_3R_71() {
    if (jj_3R_79()) return true;
    return false;
  }

  final private boolean jj_3R_37() {
    if (jj_3R_41()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_42()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  final private boolean jj_3R_70() {
    if (jj_3R_78()) return true;
    return false;
  }

  final private boolean jj_3R_66() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_70()) {
    jj_scanpos = xsp;
    if (jj_3R_71()) {
    jj_scanpos = xsp;
    if (jj_3R_72()) {
    jj_scanpos = xsp;
    if (jj_3R_73()) {
    jj_scanpos = xsp;
    if (jj_3R_74()) return true;
    }
    }
    }
    }
    return false;
  }

  final private boolean jj_3R_46() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(24)) {
    jj_scanpos = xsp;
    if (jj_scan_token(25)) {
    jj_scanpos = xsp;
    if (jj_scan_token(26)) {
    jj_scanpos = xsp;
    if (jj_scan_token(27)) return true;
    }
    }
    }
    return false;
  }

  final private boolean jj_3R_45() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(28)) {
    jj_scanpos = xsp;
    if (jj_scan_token(29)) {
    jj_scanpos = xsp;
    if (jj_scan_token(30)) {
    jj_scanpos = xsp;
    if (jj_scan_token(31)) return true;
    }
    }
    }
    return false;
  }

  final private boolean jj_3R_44() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(13)) {
    jj_scanpos = xsp;
    if (jj_scan_token(14)) {
    jj_scanpos = xsp;
    if (jj_scan_token(15)) {
    jj_scanpos = xsp;
    if (jj_scan_token(16)) return true;
    }
    }
    }
    return false;
  }

  final private boolean jj_3R_43() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(17)) {
    jj_scanpos = xsp;
    if (jj_scan_token(18)) {
    jj_scanpos = xsp;
    if (jj_scan_token(19)) {
    jj_scanpos = xsp;
    if (jj_scan_token(20)) return true;
    }
    }
    }
    return false;
  }

  final private boolean jj_3R_77() {
    if (jj_scan_token(LBRACKET)) return true;
    if (jj_3R_20()) return true;
    if (jj_scan_token(RBRACKET)) return true;
    return false;
  }

  final private boolean jj_3R_38() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_43()) {
    jj_scanpos = xsp;
    if (jj_3R_44()) {
    jj_scanpos = xsp;
    if (jj_3R_45()) {
    jj_scanpos = xsp;
    if (jj_3R_46()) return true;
    }
    }
    }
    if (jj_3R_37()) return true;
    return false;
  }

  final private boolean jj_3_1() {
    if (jj_3R_12()) return true;
    return false;
  }

  final private boolean jj_3R_35() {
    if (jj_3R_37()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_38()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  final private boolean jj_3R_40() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(32)) {
    jj_scanpos = xsp;
    if (jj_scan_token(33)) {
    jj_scanpos = xsp;
    if (jj_scan_token(34)) return true;
    }
    }
    return false;
  }

  final private boolean jj_3R_76() {
    if (jj_scan_token(DOT)) return true;
    if (jj_3R_17()) return true;
    return false;
  }

  final private boolean jj_3R_39() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(21)) {
    jj_scanpos = xsp;
    if (jj_scan_token(22)) {
    jj_scanpos = xsp;
    if (jj_scan_token(23)) return true;
    }
    }
    return false;
  }

  final private boolean jj_3R_36() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_39()) {
    jj_scanpos = xsp;
    if (jj_3R_40()) return true;
    }
    if (jj_3R_35()) return true;
    return false;
  }

  final private boolean jj_3R_69() {
    if (jj_3R_77()) return true;
    return false;
  }

  final private boolean jj_3R_33() {
    if (jj_3R_35()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_36()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  final private boolean jj_3R_68() {
    if (jj_3R_76()) return true;
    return false;
  }

  final private boolean jj_3R_65() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_68()) {
    jj_scanpos = xsp;
    if (jj_3R_69()) return true;
    }
    return false;
  }

  final private boolean jj_3R_34() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(66)) {
    jj_scanpos = xsp;
    if (jj_scan_token(67)) {
    jj_scanpos = xsp;
    if (jj_scan_token(68)) return true;
    }
    }
    if (jj_3R_33()) return true;
    return false;
  }

  final private boolean jj_3R_83() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(41)) {
    jj_scanpos = xsp;
    if (jj_scan_token(42)) return true;
    }
    if (jj_3R_20()) return true;
    return false;
  }

  final private boolean jj_3R_26() {
    if (jj_3R_33()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_34()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  final private boolean jj_3R_75() {
    if (jj_3R_20()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_83()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  final private boolean jj_3R_27() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(69)) {
    jj_scanpos = xsp;
    if (jj_scan_token(70)) {
    jj_scanpos = xsp;
    if (jj_scan_token(71)) return true;
    }
    }
    if (jj_3R_26()) return true;
    return false;
  }

  final private boolean jj_3R_67() {
    if (jj_3R_16()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(35)) {
    jj_scanpos = xsp;
    if (jj_scan_token(36)) return true;
    }
    xsp = jj_scanpos;
    if (jj_3R_75()) jj_scanpos = xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(37)) {
    jj_scanpos = xsp;
    if (jj_scan_token(38)) return true;
    }
    return false;
  }

  final private boolean jj_3R_19() {
    if (jj_3R_26()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_27()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  final private boolean jj_3_4() {
    if (jj_3R_15()) return true;
    return false;
  }

  final private boolean jj_3_3() {
    if (jj_3R_14()) return true;
    return false;
  }

  final private boolean jj_3_2() {
    if (jj_3R_13()) return true;
    return false;
  }

  final private boolean jj_3_5() {
    if (jj_3R_16()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(35)) {
    jj_scanpos = xsp;
    if (jj_scan_token(36)) return true;
    }
    return false;
  }

  final private boolean jj_3R_21() {
    if (jj_scan_token(IDENTIFIER)) return true;
    return false;
  }

  final private boolean jj_3_6() {
    if (jj_3R_17()) return true;
    if (jj_scan_token(COLON)) return true;
    return false;
  }

  final private boolean jj_3R_31() {
    if (jj_3R_19()) return true;
    return false;
  }

  final private boolean jj_3R_30() {
    if (jj_3R_15()) return true;
    return false;
  }

  final private boolean jj_3R_29() {
    if (jj_3R_14()) return true;
    return false;
  }

  final private boolean jj_3R_28() {
    if (jj_3R_13()) return true;
    return false;
  }

  final private boolean jj_3R_64() {
    if (jj_3R_21()) return true;
    return false;
  }

  final private boolean jj_3R_20() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_28()) {
    jj_scanpos = xsp;
    if (jj_3R_29()) {
    jj_scanpos = xsp;
    if (jj_3R_30()) {
    jj_scanpos = xsp;
    if (jj_3R_31()) return true;
    }
    }
    }
    return false;
  }

  final private boolean jj_3R_63() {
    if (jj_3R_67()) return true;
    return false;
  }

  final private boolean jj_3R_24() {
    if (jj_3R_17()) return true;
    if (jj_scan_token(COLON)) return true;
    return false;
  }

  final private boolean jj_3R_62() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(35)) {
    jj_scanpos = xsp;
    if (jj_scan_token(36)) return true;
    }
    if (jj_3R_20()) return true;
    xsp = jj_scanpos;
    if (jj_scan_token(37)) {
    jj_scanpos = xsp;
    if (jj_scan_token(38)) return true;
    }
    return false;
  }

  final private boolean jj_3R_61() {
    if (jj_3R_66()) return true;
    return false;
  }

  final private boolean jj_3R_59() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_61()) {
    jj_scanpos = xsp;
    if (jj_3R_62()) {
    jj_scanpos = xsp;
    if (jj_3R_63()) {
    jj_scanpos = xsp;
    if (jj_3R_64()) return true;
    }
    }
    }
    return false;
  }

  final private boolean jj_3R_16() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_24()) jj_scanpos = xsp;
    if (jj_3R_17()) return true;
    return false;
  }

  public ELParserTokenManager token_source;
  SimpleCharStream jj_input_stream;
  public Token token, jj_nt;
  private int jj_ntk;
  private Token jj_scanpos, jj_lastpos;
  private int jj_la;
  public boolean lookingAhead = false;
  private boolean jj_semLA;
  private int jj_gen;
  final private int[] jj_la1 = new int[58];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static private int[] jj_la1_2;
  static private int[] jj_la1_3;
  static {
      jj_la1_0();
      jj_la1_1();
      jj_la1_2();
      jj_la1_3();
   }
   private static void jj_la1_0() {
      jj_la1_0 = new int[] {0x0,0xfac,0xfac,0xfac,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0xfac,0x0,0x0,0x0,0x0,0xe00000,0xe00000,0x0,0xe00000,0xff1fe000,0x1e0000,0x1e000,0xf0000000,0xf000000,0xff1fe000,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x1000,0x0,0x0,0xfac,0x0,0x0,0x0,0x0,0xfac,0x0,0x1000,0xfac,0x180,0x600,0x780,};
   }
   private static void jj_la1_1() {
      jj_la1_1 = new int[] {0x0,0x803c0198,0x803c0198,0x803c0018,0x180,0x600,0x600,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x803c0018,0x0,0x0,0x0,0x0,0x7,0x0,0x7,0x7,0x0,0x0,0x0,0x0,0x0,0x0,0x3fc000,0x3c000,0x3c0000,0x3fc000,0x7fc00000,0x1c00000,0x1e000000,0x60000000,0x7fc00000,0x803c0000,0x80000000,0x3c0000,0x803c0000,0x1000,0x18,0x60,0x18,0x0,0x18,0x600,0x600,0x803c0018,0x60,0x1000,0x0,0x0,0x0,0x0,};
   }
   private static void jj_la1_2() {
      jj_la1_2 = new int[] {0x801c000,0x2801c103,0x2801c103,0x20000103,0x0,0x0,0x0,0x1800000,0x6000000,0x7800000,0x1c000,0xe0000,0x700000,0x700000,0x3c00,0x20000103,0xe0,0xe0,0x1c,0x1c,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x103,0x3,0x0,0x103,0x0,0x0,0x0,0x0,0x20000000,0x0,0x0,0x0,0x20000103,0x0,0x0,0x0,0x0,0x0,0x0,};
   }
   private static void jj_la1_3() {
      jj_la1_3 = new int[] {0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,};
   }
  final private JJCalls[] jj_2_rtns = new JJCalls[6];
  private boolean jj_rescan = false;
  private int jj_gc = 0;

  public ELParser(java.io.InputStream stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new ELParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 58; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  public void ReInit(java.io.InputStream stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 58; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  public ELParser(java.io.Reader stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new ELParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 58; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 58; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  public ELParser(ELParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 58; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  public void ReInit(ELParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 58; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  final private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      if (++jj_gc > 100) {
        jj_gc = 0;
        for (int i = 0; i < jj_2_rtns.length; i++) {
          JJCalls c = jj_2_rtns[i];
          while (c != null) {
            if (c.gen < jj_gen) c.first = null;
            c = c.next;
          }
        }
      }
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }

  static private final class LookaheadSuccess extends java.lang.Error { }
  final private LookaheadSuccess jj_ls = new LookaheadSuccess();
  final private boolean jj_scan_token(int kind) {
    if (jj_scanpos == jj_lastpos) {
      jj_la--;
      if (jj_scanpos.next == null) {
        jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
      } else {
        jj_lastpos = jj_scanpos = jj_scanpos.next;
      }
    } else {
      jj_scanpos = jj_scanpos.next;
    }
    if (jj_rescan) {
      int i = 0; Token tok = token;
      while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
      if (tok != null) jj_add_error_token(kind, i);
    }
    if (jj_scanpos.kind != kind) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
    return false;
  }

  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

  final public Token getToken(int index) {
    Token t = lookingAhead ? jj_scanpos : token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  final private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.Vector jj_expentries = new java.util.Vector();
  private int[] jj_expentry;
  private int jj_kind = -1;
  private int[] jj_lasttokens = new int[100];
  private int jj_endpos;

  private void jj_add_error_token(int kind, int pos) {
    if (pos >= 100) return;
    if (pos == jj_endpos + 1) {
      jj_lasttokens[jj_endpos++] = kind;
    } else if (jj_endpos != 0) {
      jj_expentry = new int[jj_endpos];
      for (int i = 0; i < jj_endpos; i++) {
        jj_expentry[i] = jj_lasttokens[i];
      }
      boolean exists = false;
      for (java.util.Enumeration e = jj_expentries.elements(); e.hasMoreElements();) {
        int[] oldentry = (int[])(e.nextElement());
        if (oldentry.length == jj_expentry.length) {
          exists = true;
          for (int i = 0; i < jj_expentry.length; i++) {
            if (oldentry[i] != jj_expentry[i]) {
              exists = false;
              break;
            }
          }
          if (exists) break;
        }
      }
      if (!exists) jj_expentries.addElement(jj_expentry);
      if (pos != 0) jj_lasttokens[(jj_endpos = pos) - 1] = kind;
    }
  }

  public ParseException generateParseException() {
    jj_expentries.removeAllElements();
    boolean[] la1tokens = new boolean[98];
    for (int i = 0; i < 98; i++) {
      la1tokens[i] = false;
    }
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 58; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
          if ((jj_la1_2[i] & (1<<j)) != 0) {
            la1tokens[64+j] = true;
          }
          if ((jj_la1_3[i] & (1<<j)) != 0) {
            la1tokens[96+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 98; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.addElement(jj_expentry);
      }
    }
    jj_endpos = 0;
    jj_rescan_token();
    jj_add_error_token(0, 0);
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = (int[])jj_expentries.elementAt(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  final public void enable_tracing() {
  }

  final public void disable_tracing() {
  }

  final private void jj_rescan_token() {
    jj_rescan = true;
    for (int i = 0; i < 6; i++) {
      JJCalls p = jj_2_rtns[i];
      do {
        if (p.gen > jj_gen) {
          jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
          switch (i) {
            case 0: jj_3_1(); break;
            case 1: jj_3_2(); break;
            case 2: jj_3_3(); break;
            case 3: jj_3_4(); break;
            case 4: jj_3_5(); break;
            case 5: jj_3_6(); break;
          }
        }
        p = p.next;
      } while (p != null);
    }
    jj_rescan = false;
  }

  final private void jj_save(int index, int xla) {
    JJCalls p = jj_2_rtns[index];
    while (p.gen > jj_gen) {
      if (p.next == null) { p = p.next = new JJCalls(); break; }
      p = p.next;
    }
    p.gen = jj_gen + xla - jj_la; p.first = token; p.arg = xla;
  }

  static final class JJCalls {
    int gen;
    Token first;
    int arg;
    JJCalls next;
  }

}
